In [1]:
import cvxpy as cp
import numpy as np

# (1)


In [2]:
x = cp.Variable(3, integer=True)

prob = cp.Problem(
    cp.Minimize(5 * x[0] - x[1] + 2 * x[2]),
    [
        2 * x[0] - x[1] + 4 * x[2] <= 4,
        x[0] + x[1] + 2 * x[2] <= 5,
        -2 * x[0] + x[1] - x[2] <= -1,
        x >= 0,
    ],
)
prob.solve(solver=cp.GLPK_MI)

display(prob.status, x.value, prob.value)

'optimal'

array([0., 0., 1.])

np.float64(2.0)

# Problem


## -1


In [3]:
x = cp.Variable(9, boolean=True)

A = np.array(
    [
        [1, 0, 0, 1, 1, 0, 0, 1, 1],
        [0, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 1, 1],
    ]
)
k, _ = A.shape

prob = cp.Problem(cp.Minimize(cp.sum(x)), [A @ x >= np.ones(k)])
prob.solve(solver=cp.GLPK_MI)

display(prob.status, x.value, prob.value)

'optimal'

array([1., 1., 0., 0., 1., 0., 0., 0., 0.])

np.float64(3.0)

## -2


In [4]:
x = cp.Variable(3, integer=True)

c = np.array([5, 8, 6])
A = np.array([[9, 6, 10], [20, 63, 10]])
b = np.array([14, 110])

prob = cp.Problem(cp.Maximize(c @ x), [A @ x <= b, x >= 0])
prob.solve(solver=cp.GLPK_MI)

display(prob.status, x.value, prob.value)

'optimal'

array([0., 1., 0.])

np.float64(8.0)

## -3


In [5]:
# period-1 on -> period-2 on

x = cp.Variable(3 * 2, boolean=True)

prob = cp.Problem(
    cp.Minimize(
        2800 * x[3]
        + 2000 * x[4]
        + 1900 * x[5]
        + 5 * 1900 * (x[0] + x[3])
        + 3 * 1700 * (x[1] + x[4])
        + 8 * 2900 * (x[2] + x[5])
    ),
    [
        1900 * x[0] + 1700 * x[1] + 2900 * x[2] >= 2500,
        1900 * x[3] + 1700 * x[4] + 2900 * x[5] >= 3500,
        x[0] <= x[3],
        x[1] <= x[4],
        x[2] <= x[5],
    ],
)
prob.solve(solver=cp.GLPK_MI)

display(prob.status, x.value, prob.value)

'optimal'

array([1., 1., 0., 1., 1., 0.])

np.float64(34000.0)

## -4


In [6]:
x = cp.Variable(3 * 2, integer=True)

c = np.array(
    [
        26 * (80 / 1000) + 2.5,
        25 * (80 / 1000) + 2.5,
        22 * (80 / 1000) + 2.5,
        21 * (80 / 1000) + 2.8,
        28 * (80 / 1000) + 2.8,
        30 * (80 / 1000) + 2.8,
    ]
)
A = np.array([[1, 0, 0, 1, 0, 0], [0, 1, 0, 0, 1, 0], [0, 0, 1, 0, 0, 1]])
b = np.array([5000, 7000, 4000])

prob = cp.Problem(cp.Minimize(c @ x), [A @ x >= b, x >= 0])
prob.solve(solver=cp.GLPK_MI)

display(prob.status, x.value, prob.value)

'optimal'

array([   0., 7000., 4000., 5000.,    0.,    0.])

np.float64(70940.0)

## -5


In [7]:
x = cp.Variable(3, integer=True)

c = np.array([2, 1, 3])
A = np.array([[1, 1, 3], [3, 2, 2]])
b = np.array([17, 11])

prob = cp.Problem(cp.Maximize(c @ x), [A @ x <= b, x >= 0])
prob.solve(solver=cp.GLPK_MI)

display(prob.status, x.value, prob.value)

'optimal'

array([0., 0., 5.])

np.float64(15.0)